[workspace]
members = [
    "crates/rustle-lang",
    "crates/rustle-renderer",
    "crates/rustle-ide",
    "crates/rustle-cli",
]
resolver = "2"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
redundant_clone = "warn"
large_enum_variant = "warn"
needless_collect = "warn"
