name: Bug Report
description: Report a bug, unexpected behavior, or missing feature
title: "[bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please fill in as much detail as you can.

  - type: textarea
    id: script
    attributes:
      label: Script
      description: Paste the exact script that caused the problem. Even a small minimal example helps.
      render: rust
      placeholder: |
        import shapes { circle }
        out << circle(vec2(0.0, 0.0), 0.3)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages, error codes (e.g. S001), or a description of what was rendered incorrectly.
    validations:
      required: true

  - type: dropdown
    id: kind
    attributes:
      label: Kind of problem
      options:
        - Compile error on code that should work
        - No compile error on code that should fail
        - Wrong output (wrong shape, wrong position, wrong color)
        - Runtime crash or panic
        - Documentation is wrong or missing
        - Other
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Anything else that might be relevant — what you tried, what you expected from the docs, etc.
    validations:
      required: false
