[package]
name = "rustle-ide"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
rustle-lang = { version = "0.1.0", path = "../rustle-lang" }
rustle-renderer = { version = "0.1.0", path = "../rustle-renderer" }
eframe = { version = "^0.34.1", features = ["wgpu"] }
egui = "0.34.1"
egui-wgpu = "0.34.2"
wgpu = "29.0.3"
rfd = "0.17.2"
alacritty_terminal = "0.25.0"
open = "5.3.2"
ropey = "1.6"
